### ISSUE TITLE
TypeError: structure.getStructureName is not a function

### ISSUE THREAD

**Issue by bdew** [woubuc/WurmMapGen#1]
```
map.js:139 Uncaught (in promise) TypeError: structure.getStructureName is not a function
    at Object.create (map.js:139)
    at main.js:69
    at <anonymous>
```

After the error the left pane shows empty and the map doesn't show any markers.

If you want to look at the generated files they are here - https://www.dropbox.com/s/dlruhzilkph6mmo/avalon.zip?dl=0

**Comment by woubuc** [comment]
This should be fixed now in [RC3](https://github.com/woubuc/WurmMapGen/releases/tag/v2.0.0-rc3).
