### ISSUE TITLE
Editing template

### ISSUE THREAD

**Issue by woubuc** [woubuc/WurmMapGen#1]
I'd like to add some changes and extra features to the map template, how would I go about adding Javascript code to the HTML template in the repository?

**Comment by woubuc** [comment]
Pinging @Garrett92

**Comment by Garrett92** [comment]
Hey, what exactly are you trying to add? The map uses leaflet, so you
should be able to check out some of their tutorials. http://leafletjs.com

**Comment by woubuc** [comment]
I built the [Sklotopolis online map tool](http://andistyr.github.io/wu-map/) a while back, and I would like to add some of the same features (mostly deed search and marking home deeds) to this repo as a PR. The reason being that (World of Wonders)[https://worldofwonders.enjin.com/], the server I'm currently playing on, uses this one for their live map and I'd like to improve it a bit.

I don't see any html or js files in the repo, so that was the reason for my question. Are all files included in the .zip file in the repo? And if so, is there a particular reason for them being in a zip file?

**Comment by Garrett92** [comment]
I honestly don't remember why I used a zip file to store them. But yeah,
all the html and js files should be located in the zip. If I remember
correctly, there might be a couple that are generated during the map gen as
well.

**Comment by woubuc** [comment]
Great, will take a look at the code. I'll probably unpack and commit the files separately if I make a PR though. Thanks for the feedback!
