### ISSUE TITLE
License

### ISSUE THREAD

**Issue by woubuc** [woubuc/WurmMapGen#2]
I noticed the repository doesn't have a license listed. Is this on purpose or you just didn't add one yet @Garrett92 ?

**Comment by Garrett92** [comment]
No reason. I'm a total noob when it comes to git and this project was the
first I've posted to github. Feel free to make any changes, let me know if
I need to change something to make it easier.

**Comment by woubuc** [comment]
Might be best if you add the license to the repo, that way you can choose a license you like.

**Comment by woubuc** [comment]
@Garrett92 any progress on this? I'm hesitant to make changes if you haven't added a clear license to your project.

FYI, having no license essentially means "no rights given to anyone". You can add a license by simply adding a `LICENSE.txt` file to your repository with the necessary license text. If you're not sure which license to use, try [choosealicense.com](https://choosealicense.com/), one of those is usually good for code on Github.

**Comment by Garrett92** [comment]
Sorry about that, the licence is there now.

**Comment by woubuc** [comment]
Awesome, thanks!
