### ISSUE TITLE
RMI documentation

### ISSUE THREAD

**Issue by woubuc** [woubuc/WurmMapGen#3]
Is there any documentation on setting up the RMI part?

**Comment by Garrett92** [comment]
The only documentation I have is located on the github page. 
https://github.com/Garrett92/WurmWebRMI

All you need for the map viewer is point 'includes/rmi.php' to the RMI tool.
The default is set to $GLOBALS['RMI_ADDRESS'] = "localhost:8080";

**Comment by woubuc** [comment]
Thanks for the link! It took me a bit of figuring out but I got it working, and I was able to finish that part of the GUI update as well. See PR #4.
